---
# tasks file for replayed
# Create directories up front
# Note: elastalrt does not run as root!
# - name: Create directories for replayed
#   file:
#     path: "{{ item }}"
#     state: directory
#     owner: "root"
#     group: "root"
#     mode: 0750
#   with_items:
#     - "{{ replayed_config_dir }}"

# - name: Copy binary to distination
#   copy:
#     src: replayed.linux.amd64
#     dest: "{{ replayed_binary_loc }}"
#     owner: root
#     group: root
#     mode: 0700

# - name: Copy config replayed_config.json file
#   template:
#     src: templates/replayed_config.json
#     dest: /etc/replayed/replayed.conf
#     #{{ replayed_config_file }}
#     owner: root
#     group: root
#     mode: 0600

# - name: Example of async and poll
#   hosts: all
#   tasks:
#     - name: Run scripts
#       command: "echo hi"
#       async: 100
#       poll: 25
#       with_items:
#         - fill_database
#         - create_users
#       register: result

- hosts: all
  remote_user: opc
  tasks:
  - name: simulate long running op (15 sec), wait for up to 45 sec, poll every 5 sec
    command: /bin/sleep 15
    async: 45
    poll: 5